import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown, HelpCircle } from 'lucide-react';

const faqs = [
  {
    question: "Do I need to know Docker to use this?",
    answer: "While basic knowledge helps, Deploit is designed to abstract away the complexity. You just need to run the script, and it handles the Docker containerization for you."
  },
  {
    question: "Is it safe to use in production?",
    answer: "Yes. We use standard, production-ready Nginx configurations and official Docker images. SSL is handled via Let's Encrypt, which is the industry standard for free, secure certificates."
  },
  {
    question: "Can I host multiple applications on one server?",
    answer: "Absolutely. Deploit sets up Nginx as a reverse proxy, allowing you to host multiple different applications on different subdomains (e.g., app1.domain.com, app2.domain.com) on a single VPS."
  },
  {
    question: "How do I update the applications?",
    answer: "Since everything is containerized, updating is usually as simple as pulling the new Docker image and restarting the container. We are working on an update script to automate this further."
  },
  {
    question: "Where are the SSL certificates stored?",
    answer: "Certificates are generated by Certbot and stored in a Docker volume. They are automatically renewed by the Certbot container, so you don't have to worry about expiration."
  }
];

export const FAQ = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section className="px-4 pt-16 pb-8">
      <div className="max-w-3xl mx-auto">
        <motion.h2 
          initial={{ opacity: 0, x: -20 }}
          whileInView={{ opacity: 1, x: 0 }}
          viewport={{ once: true }}
          className="text-3xl md:text-4xl font-bold mb-12 text-center text-green-400"
        >
          &lt;KnowledgeBase /&gt;
        </motion.h2>

        <div className="flex flex-col gap-4">
          {faqs.map((faq, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 10 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.1 }}
              className="border border-gray-800 rounded-lg bg-gray-900/30 overflow-hidden"
            >
              <button
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                className="w-full px-6 py-4 flex items-center justify-between text-left hover:bg-gray-800/50 transition-colors"
              >
                <span className="text-gray-200 font-mono flex items-center gap-3">
                  <HelpCircle size={16} className="text-green-500 min-w-4 min-h-4" />
                  {faq.question}
                </span>
                <ChevronDown 
                  className={`text-gray-500 transition-transform duration-300 ${openIndex === index ? 'rotate-180' : ''}`}
                  size={20}
                />
              </button>
              <AnimatePresence>
                {openIndex === index && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3 }}
                  >
                    <div className="px-6 pb-4 text-gray-400 text-sm leading-relaxed border-t border-gray-800/50 pt-4 ml-9">
                      {faq.answer}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};
